### ISSUE TITLE
Publish a new nuget package compatible with FSharp.Core 5 and support for netstandard 2.0

### ISSUE THREAD

**Issue by smoothdeveloper** [matthewcrews/flips#88]
I was looking to try the library using `#r "nuget: Flips"` but there is a warning because fsi uses FSharp.Core 5, and it seems netstandard2.1 isn't usable from .net framework.

![image](https://user-images.githubusercontent.com/87944/99104893-76991c80-2596-11eb-81f9-d07d281126b3.png)

Is it possible to retarget the library to netstandard2.0 and mark the nuget package compatible with fsharp.core 5?

**Comment by matthewcrews** [comment]
I'll look into it this evening

**Comment by matthewcrews** [comment]
@smoothdeveloper There's a new version released (2.3.5) which has these changes. I've tested writing a net5.0 app and everything seems to work. Thanks for the PR!

**Comment by smoothdeveloper** [comment]
@matthewcrews thanks, it loads in FSI from Visual Studio now, the next issue is loading the native dependency, I'm not sure there is an easy built-in way for this:

> System.TypeInitializationException: The type initializer for 'Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'google-ortools-native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_linear_solver(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper..ctor()
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.Solver_CreateSolver(String jarg1)
   at Google.OrTools.LinearSolver.Solver.CreateSolver(String solver_id)
   at Flips.ORTools.solve(OrToolsSolverType solverType, SolverSettings settings, Model model)
   at FSI_0007.solve() in C:\work\flips.fsx:line 10
   at <StartupCode$FSI_0008>.$FSI_0008.main@()

**Comment by smoothdeveloper** [comment]
Ok, here is a workaround for using in VS:

```fsharp

#r "nuget: NativeLibraryLoader"
open NativeLibraryLoader
new NativeLibrary(@"path\to\libz3.dll")
new NativeLibrary(@"path\to\google-ortools-native.dll")
```

**Comment by matthewcrews** [comment]
Huh, that's weird. That's seems like a regression on the Microsoft side. We had an issue with the native library loader in beta but they fixed it. Seems like it broke again.
